package dev.lysmux.lab8.common.collection.model;

import dev.lysmux.lab8.common.collection.validator.annotations.AutoGenerated;
import dev.lysmux.lab8.common.collection.validator.annotations.Min;
import dev.lysmux.lab8.common.collection.validator.annotations.NotEmpty;
import dev.lysmux.lab8.common.collection.validator.annotations.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.ZoneId;

/**
 * LabWork class
 *
 * @see Coordinates
 * @see Difficulty
 * @see Person
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class LabWork implements Comparable<LabWork>, Serializable {
    /**
     * LabWork ID
     * <p>Field can not be {@code null} and must be greater than {@code 0}
     * and must be {@code autogenerated}</p>
     */
    @NotNull
    @Min(0)
    @AutoGenerated
    private Integer id = -1;

    /**
     * LabWork owner ID
     * <p>Field can not be {@code null} and must be greater than {@code 0}
     * and must be {@code autogenerated}</p>
     */
    @NotNull
    @Min(0)
    @AutoGenerated
    private Integer ownerId = -1;

    /**
     * LabWork name
     * <p>Field can not be {@code null} or {@code empty}</p>
     */
    @NotNull
    @NotEmpty
    private String name;

    /**
     * LabWork minimal point
     * <p>Field must be greater that {@code 0}</p>
     */
    @Min(0)
    private long minimalPoint;

    /**
     * LabWork difficulty
     * <p>Field can not be {@code null}</p>
     *
     * @see Difficulty
     */
    @NotNull
    private Difficulty difficulty;

    /**
     * LabWork creation date
     * <p>Field can not be {@code null} and must be {@code autogenerated}</p>
     */
    @NotNull
    @AutoGenerated
    private LocalDate creationDate = LocalDate.now(ZoneId.systemDefault());

    /**
     * LabWork coordinates
     * <p>Field can not be {@code null}</p>
     *
     * @see Coordinates
     */
    @NotNull
    private Coordinates coordinates;

    /**
     * LabWork author
     * <p>Field can not be {@code null}</p>
     *
     * @see Person
     */
    @NotNull
    private Person author;

    /**
     * Compares entities by coordinate
     *
     * @param o the object to be compared
     * @return the value {@code 0} if {@code x == y};
     * a value less than {@code 0} if {@code x < y}; and
     * a value greater than {@code 0} if {@code x > y}
     */
    @Override
    public int compareTo(LabWork o) {
        return coordinates.compareTo(o.coordinates);
    }
}