package dev.lysmux.lab6.common.handler;


import dev.lysmux.lab6.common.collection.validator.ValidationException;
import dev.lysmux.lab6.common.collection.validator.Validator;
import dev.lysmux.lab6.common.collection.validator.annotations.AutoGenerated;
import dev.lysmux.lab6.common.command.CommandRegistry;
import dev.lysmux.lab6.common.command.exception.CommandNotFoundException;
import dev.lysmux.lab6.common.command.meta.CommandArg;
import dev.lysmux.lab6.common.command.wrapper.CommandWrapper;
import dev.lysmux.lab6.common.dto.Response;
import dev.lysmux.lab6.common.handler.exception.CouldNotParseObjectException;
import dev.lysmux.lab6.common.handler.exception.NoSuchArgException;
import dev.lysmux.lab6.common.handler.parser.ArgParser;
import dev.lysmux.lab6.common.handler.parser.CouldNotParseArgException;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.List;


@RequiredArgsConstructor
abstract public class Handler {
    @NonNull
    private final CommandRegistry commandRegistry;

    /**
     * Handles string input
     *
     * @param input input to handle
     * @return execution result
     * @throws CommandNotFoundException  if command not found
     * @throws NoSuchArgException        if needed argument not provided
     * @throws CouldNotParseArgException if argument could not be parsed
     * @throws ValidationException       if argument is not valid
     */
    public Response handleInput(String input) throws
            CommandNotFoundException,
            NoSuchArgException,
            CouldNotParseArgException,
            ValidationException {
        String[] tokens = input.split("\\s+");
        String commandName = tokens[0];
        String[] args = tokens.length > 1
                ? Arrays.copyOfRange(tokens, 1, tokens.length)
                : new String[0];

        CommandWrapper command = commandRegistry.getCommand(commandName);
        Object[] parsedArgs = parseArgs(command, args);

        return command.execute(parsedArgs);
    }

    /**
     * Parses command arguments
     *
     * @param command     requested command
     * @param requestArgs provided arguments
     * @return command arguments
     * @throws NoSuchArgException        if needed argument not provided
     * @throws CouldNotParseArgException if argument could not be parsed
     * @throws ValidationException       if argument is not valid
     */
    private Object[] parseArgs(CommandWrapper command, String[] requestArgs) throws
            NoSuchArgException,
            CouldNotParseArgException,
            ValidationException {
        List<CommandArg> commandArgs = command.getArgs();
        Object[] args = new Object[commandArgs.size()];

        int i = 0;
        for (var cmdArg : commandArgs) {
            if (!ArgParser.canParse(cmdArg.type())) {
                args[i] = parseObject(cmdArg.type());
            } else if (i < requestArgs.length) {
                args[i] = ArgParser.parseArg(requestArgs[i], cmdArg.type());
            } else {
                throw new NoSuchArgException(command, cmdArg.name());
            }
            i++;
        }

        return args;
    }

    /**
     * Parses complex object
     *
     * @param objClass object class to parse
     * @param <T>      type of object
     * @return parsed object
     * @throws ValidationException       if object property is invalid
     * @throws CouldNotParseArgException if object property could not be parsed
     */
    private <T> T parseObject(Class<T> objClass) throws ValidationException, CouldNotParseArgException {
        T obj;
        try {
            obj = objClass.getDeclaredConstructor().newInstance();
        } catch (ReflectiveOperationException e) {
            throw new CouldNotParseObjectException("No default public constructor found for %s".formatted(objClass.getSimpleName()));
        }

        for (var field : objClass.getDeclaredFields()) {
            if (field.isAnnotationPresent(AutoGenerated.class)) continue;

            field.setAccessible(true);
            try {
                if (ArgParser.canParse(field.getType())) {
                    field.set(obj, parseObjectField(objClass, field));
                } else {
                    field.set(obj, parseObject(field.getType()));
                }
            } catch (ReflectiveOperationException e) {
                throw new CouldNotParseObjectException("Could not set field %s".formatted(field.getName()));
            }
        }

        return obj;
    }

    /**
     * Gets object property
     *
     * @param objClass object class that is being parsed
     * @param field    field that is being parsed
     * @return object property
     */
    abstract protected String requestProperty(Class<?> objClass, Field field);

    /**
     * Parses object field
     *
     * @param objClass object class that is being parsed
     * @param field    field that is being parsed
     * @return parsed field
     * @throws ValidationException       if field value is not valid
     * @throws CouldNotParseArgException if field value could not be parsed
     */
    protected Object parseObjectField(Class<?> objClass, Field field) throws
            ValidationException, CouldNotParseArgException {
        String input = requestProperty(objClass, field);
        Object parsed = ArgParser.parseArg(input, field.getType());
        Validator.validateField(field, parsed);
        return parsed;
    }
}
