package dev.lysmux.lab5.handler;

import dev.lysmux.lab5.collection.validator.ValidationException;
import dev.lysmux.lab5.collection.validator.Validator;
import dev.lysmux.lab5.collection.validator.annotations.AutoGenerated;
import dev.lysmux.lab5.controller.CommandManager;
import dev.lysmux.lab5.controller.CommandWrapper;
import dev.lysmux.lab5.controller.exception.CommandNotFoundException;
import dev.lysmux.lab5.handler.exception.CouldNotParseObjectException;
import dev.lysmux.lab5.handler.exception.NoSuchArgException;
import dev.lysmux.lab5.handler.parser.ArgParser;
import dev.lysmux.lab5.handler.parser.CouldNotParseArgException;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.Collection;


/**
 * Abstract class for handle string inputs
 *
 * @since 1.0
 */
@RequiredArgsConstructor
abstract public class Handler {
    @NonNull
    private final CommandManager commandManager;

    /**
     * Handles string input
     *
     * @param input input to handle
     * @return execution result
     * @throws CommandNotFoundException  if command not found
     * @throws NoSuchArgException        if needed argument not provided
     * @throws CouldNotParseArgException if argument could not be parsed
     * @throws ValidationException       if argument is not valid
     */
    public String handleInput(String input) throws
            CommandNotFoundException,
            NoSuchArgException,
            CouldNotParseArgException,
            ValidationException {
        Request request = parseRequest(input);
        CommandWrapper command = commandManager.getCommand(request.commandName());
        Object[] parsedArgs = parseArgs(command, request.args());

        return command.execute(parsedArgs).toString();
    }

    /**
     * Parses string input to {@link Request}
     *
     * @param input input to parse
     * @return parsed request
     */
    private Request parseRequest(String input) {
        String[] tokens = input.split("\\s+");
        String commandName = tokens[0];
        String[] args = tokens.length > 1
                ? Arrays.copyOfRange(tokens, 1, tokens.length)
                : new String[0];

        return new Request(commandName, args);
    }

    /**
     * Parses command arguments
     *
     * @param command     requested command
     * @param requestArgs provided arguments
     * @return command arguments
     * @throws NoSuchArgException        if needed argument not provided
     * @throws CouldNotParseArgException if argument could not be parsed
     * @throws ValidationException       if argument is not valid
     */
    private Object[] parseArgs(CommandWrapper command, String[] requestArgs) throws
            NoSuchArgException,
            CouldNotParseArgException,
            ValidationException {
        Collection<Class<?>> commandArgs = command.getArgs().values();
        Object[] args = new Object[commandArgs.size()];

        int i = 0;
        for (var cmdArg : commandArgs) {
            if (!ArgParser.canParse(cmdArg)) {
                args[i] = parseObject(cmdArg);
            } else if (i < requestArgs.length) {
                args[i] = ArgParser.parseArg(requestArgs[i], cmdArg);
            } else {
                throw new NoSuchArgException(command, cmdArg.getSimpleName());
            }
            i++;
        }

        return args;
    }

    /**
     * Parses complex object
     *
     * @param objClass object class to parse
     * @param <T>      type of object
     * @return parsed object
     * @throws ValidationException       if object property is invalid
     * @throws CouldNotParseArgException if object property could not be parsed
     */
    private <T> T parseObject(Class<T> objClass) throws ValidationException, CouldNotParseArgException {
        T obj;
        try {
            obj = objClass.getDeclaredConstructor().newInstance();
        } catch (ReflectiveOperationException e) {
            throw new CouldNotParseObjectException("No default public constructor found for %s".formatted(objClass.getSimpleName()));
        }

        for (var field : objClass.getDeclaredFields()) {
            if (field.isAnnotationPresent(AutoGenerated.class)) continue;

            field.setAccessible(true);
            try {
                if (ArgParser.canParse(field.getType())) {
                    field.set(obj, parseObjectField(objClass, field));
                } else {
                    field.set(obj, parseObject(field.getType()));
                }
            } catch (ReflectiveOperationException e) {
                throw new CouldNotParseObjectException("Could not set field %s".formatted(field.getName()));
            }
        }

        return obj;
    }

    /**
     * Gets object property
     *
     * @param objClass object class that is being parsed
     * @param field    field that is being parsed
     * @return object property
     */
    abstract protected String requestProperty(Class<?> objClass, Field field);

    /**
     * Parses object field
     *
     * @param objClass object class that is being parsed
     * @param field    field that is being parsed
     * @return parsed field
     * @throws ValidationException       if field value is not valid
     * @throws CouldNotParseArgException if field value could not be parsed
     */
    protected Object parseObjectField(Class<?> objClass, Field field) throws
            ValidationException, CouldNotParseArgException {
        String input = requestProperty(objClass, field);
        Object parsed = ArgParser.parseArg(input, field.getType());
        Validator.validateField(field, parsed);
        return parsed;
    }
}
